id: D508CC8A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:07:03+00:00'
last_modified: '2022-05-27T09:43:38.955251+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    43db:
      image_group_id: I1PD95905
      title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་ཚིག་གསལ་བ།
      total_pages: 1913
      order: 60
      base_file: 43db.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
