id: PCAD2C00D
initial_creation_type: ocr
source_metadata:
  volumes:
    bf404f3449c54aa3bb6ea41b9ff1f43c:
      base_file: v060.txt
      image_group_id: I1PD95905
      title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་ཚིག་གསལ་བ།
      total_pages: 1913
      volume_number: 60
vol2fn:
  v060: v060.txt